services:
  postgres:
    image: postgres:17
    container_name: cobudekjidlu-postgres
    environment:
      POSTGRES_DB: cobudekjidlu
      POSTGRES_USER: cobudekjidlu
      POSTGRES_PASSWORD: cobudekjidlu
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

