databases:
  - name: cobudekjidlu-db
    plan: free
    databaseName: cobudekjidlu
    user: cobudekjidlu

services:
  - type: web
    name: cobudekjidlu-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DB_URL
        fromDatabase:
          name: cobudekjidlu-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: cobudekjidlu-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cobudekjidlu-db
          property: password
      - key: FRONTEND_URL
        value: https://matthew-kulich.github.io
